# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[plugins]

[plugins.highlight]
github = "zdharma-continuum/fast-syntax-highlighting"

[plugins.bat]
github = "fdellwing/zsh-bat"

[plugins.exa]
github = "mdarrint/zsh-aliases-exa"

[plugins.tips]
github = "djui/alias-tips"

[plugins.suggesstions]
github = "zsh-users/zsh-autosuggestions"

[plugins.git-extra]
github = "tj/git-extras"

[plugins.git-prompt]
github = "olivierverdier/zsh-git-prompt"

[plugins.git-open]
github = "paulirish/git-open"

#[plugins.you-should-use]
#github = "MichaelAquilina/zsh-you-should-use"

[plugins.autopair]
github = "hlissner/zsh-autopair"
[plugins.enhanced]
github = "babarot/enhancd"

[plugins.autojump]
github = "wting/autojump"
dir = "bin"
apply = ["PATH", "source"]

[plugins.powerlevel10k]
github = "romkatv/powerlevel10k"

[plugins.codex]
github = "tom-doerr/zsh_codex"

[plugins.vi]
github = "jeffreytse/zsh-vi-mode"

[plugins.direnv]
github = "ptavares/zsh-direnv"

[plugins.colored_man]
github = "ael-code/zsh-colored-man-pages"

# For example:
#
# [plugins.base16]
# github = "chriskempson/base16-shell"
#
